name = "DualArray"
uuid = "2d303a2e-ed0f-4387-b085-e4f1b0160ad5"
authors = ["RuQing Xu <r-xu@g.ecc.u-tokyo.ac.jp>"]
version = "0.1.0"

[deps]
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
TensorOperations = "3.0"
julia = "1.4"
